name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Build
        run: zig build

      - name: Test
        run: zig build test

      - name: Test 32-bit
        # TODO: Re-enable Windows, see https://github.com/ziglang/zig/issues/20047
        if: ${{ matrix.os != 'macos-latest' && matrix.os != 'windows-latest' }}
        run: zig build test -Dtarget=x86-native
